// Generated by CoffeeScript 1.6.3
exports.index = function(request, response) {
  return response.render("index");
};

exports.log = function(request, response) {
  var filename, fs;
  fs = require('fs');
  if (request.method === 'POST') {
    filename = "./log/log.json";
    return fs.appendFile(filename, JSON.stringify(request.body) + ",", function(err) {
      if (err) {
        return console.log(err);
      } else {
        return response.send("JSON accepted");
      }
    });
  }
};
