// Generated by CoffeeScript 1.6.3
exports.setEnv = function(environment) {
  /*
    Common config
  */

  exports.HOSTNAME = "localhost";
  exports.PORT = 8010;
  exports.PUBLIC_PATH = "public";
  exports.VIEWS_ENGINE = "jade";
  exports.VIEWS_PATH = "views";
  exports.IMAGES_PATH = "images";
  exports.DATA_PATH = "data";
  /*
    Environment specific config
  */

  switch (environment) {
    case "development":
      return null;
    case "testing":
      return null;
    case "production":
      return null;
    default:
      return console.log("Unknown environment " + environment + "!");
  }
};
